project_id: '588043'
api_token: CROWDIN_API_TOKEN
base_path: .
base_url: 'https://api.crowdin.com'
preserve_hierarchy: 1
files:
  - source: /Docs/md/**/*.md
    ignore:
      - /Docs/md/i18n/**/*.md
    translation: /Docs/md/i18n/%locale%/**/%original_file_name%
  - source: /Yet-Another-HoYo-Launcher/Strings/en-US/*.resw
    translation: /Yet-Another-HoYo-Launcher/Strings/%locale%/%original_file_name%
  - source: /README.md
    translation: /Docs/md/i18n/%locale%/README.md
